### ISSUE TITLE
How we can integrate Xtext Language Server to Eclipse Che?

### ISSUE THREAD

**Issue by chetanladdha** [itemis/xtext-languageserver-example#20]
As Che is also compatible with LSP.  Do we have any example/documentation for integrating with Eclipse Che?  
From Xtext file, can we generate the Xtext based editor from this protocol? Is there any documentation?

**Comment by cdietrich** [comment]
No there is no documentation.
che language server is still in work so it works only with some hardcoding.
https://github.com/cdietrich/che/tree/xtext2

=> nothing you can use out of the box

**Comment by chetanladdha** [comment]
Thanks @cdietrich. Could you please provide more pointer on which kind of hardcoding?

**Comment by cdietrich** [comment]
see my last commits 

https://github.com/cdietrich/che/commit/d2b5b1a8ed0056e726143bf05cd45c1d24c8dfab
https://github.com/cdietrich/che/commit/8a7d85c3b5e8e520a86efa521d77a7ea325db350
https://github.com/cdietrich/che/commit/bc9b6916b87a79986da9018e8e9030536e8144a0

https://github.com/eclipse/che/issues/3127

**Comment by chetanladdha** [comment]
Thank You @cdietrich. !!
Do you mean with hard coding, we can have Che and Xtext integration?  
Does this Xtext version will generate language registrations to META-INF/services/* for Java Servers and ships with a main class to start a language server, so that I can register it with Che and start server?

**Comment by cdietrich** [comment]
i cannot follow you

- xtext 2.11 has language server support and has a main class you can usew
- you can use e.g. gradle shadow jar plugin to create a shadowjar or gradle application plugin to create a launch.bat/sh (the initial version of the repo did a showdowjar, the current uses a appplication launch bat/sh)
- che support language servers
- you add a plugin to che to associate a file extension with a way to launch a language server
- you add a agent to che that sideloads (downloads) the language server (in my example it downloads the jar, in other cases it would download a zipped application) so that i can be started by the plugin
- the che language server support currently has so bugs. this bugs prevent from xtext language server working. you can mitigate/patch/workaround some places in che code which makes them usable with your language server only and no others.

my che branch/fork contains everything to get the language server of this repo in the older version with a showdow jar running

**Comment by chetanladdha** [comment]
Thanks, it answers most of my questions. In above reply, I am still not clear with the second point. Why need to create shadow jar plugin, how it impacts?
Also, does this patch working with Color coding, Code assistance etc in Che for sample dsl ?

**Comment by cdietrich** [comment]
i still dont get your question. the language client (che/vscode) needs to start the server somehow. in java you can do this

`java -jar myjar.jar` // with myjar beeing a self contained full jar with main class in manifest. this is what a showdaow jar is.
`java -cp .... a.b.c.Main` // this is what the gradle application plugin gives you.

in my example i dont care about synatax coloring since this is not part of the language server protocol yet but a client specific thing. and yes it supports all language server features that xtext and che support. and ys it is working (as i said with a patched che to mitigate che bugs)

**Comment by chetanladdha** [comment]
Thank you !! 
That make sense for me now.  I am trying to play with [your ](https://github.com/cdietrich/che/tree/xtext2)code, I tried on couple of systems to build your code but I am getting below compilation failures, any chance if you have seen it:

` Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project assembly-wsagent-war: Compilation failure: Compilation failure:
[ERROR] warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.8'
[ERROR] C:\dsl\che\assembly\assembly-wsagent-war\src\main\java\org\eclipse\che\wsagent\server\CheWebSocketEndpoint.java:[15,46] error: cannot find symbol
[ERROR] symbol:   class PendingMessagesReSender`

Maven -v output:
`λ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: C:\Softwares\apache-maven-3.3.9
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_25\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"`

Any pointer will be helpful.

**Comment by cdietrich** [comment]
i have no idea.i simply do a mvn clean install -Pfast

**Comment by chetanladdha** [comment]
It got compiled with -Pfast option, not directly with mvn clean install, 
but getting below error while starting server: 
λ che.bat
`An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json: open //./pipe/docker_engine: The system cannot find the file specified.`

Any thought ?

**Comment by cdietrich** [comment]
what do you do to start che.

i do `docker run -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DEBUG_SERVER=true -e CHE_ASSEMBLY=/home/dietrich/che/assembly/assembly-main/target/eclipse-che-5.0.0-M8-SNAPSHOT/eclipse-che-5.0.0-M8-SNAPSHOT/ codenvy/che-launcher:nightly start`

**Comment by chetanladdha** [comment]
Thanks @cdietrich. It was Windows specific issue mentioned at https://github.com/eclipse/che/issues/2449, 
I am able to start the che but facing issue while creating the project:
Getting error while creating project `Unable create new file. Item specified as parent is not a folder`.

I am debugging issue, let me know if you have seen before.
 It would be great if you can list down the steps you followed to run this branch? (If you have done anything extra other than normal che starting steps)

**Comment by cdietrich** [comment]
do you create the PHP project?

**Comment by chetanladdha** [comment]
Yes...

**Comment by cdietrich** [comment]
sry i have no idea on this.

**Comment by cdietrich** [comment]
i rebased after the hardcoding is no longer needed: https://github.com/cdietrich/che/tree/xtext2rx

**Comment by chetanladdha** [comment]
Great @cdietrich.

**Comment by chetanladdha** [comment]
@cdietrich : Could you please let me know how you generated mydsl.jar, is this just simple jar created/exported from eclipse? Have you use latest Xtext 2.11 beta version for the creation of MyDSL project ?

**Comment by cdietrich** [comment]
i used this project here in the version before the switch to the gradle application plugin
(https://github.com/itemis/xtext-languageserver-example/tree/379f7ac28d5b16ee00a71b560471ff6f6c55721a)

and yes i use xtext 2.11 and no i did some manual changes to the project to create the shadow jar.
but: if you use xtext 2.11 it will generate the java service loader config that is needed

**Comment by chetanladdha** [comment]
Thanks @cdietrich. 

I am playing with your https://github.com/cdietrich/che/tree/xtext2rx prototype but it's blocked with below message, it's not moving ahead, any thought ?
![image](https://cloud.githubusercontent.com/assets/16016268/21133604/98019420-c13f-11e6-80fb-a8c9ac0b4534.png)

**Comment by cdietrich** [comment]
have no idea

- make a new workspace
- create a project
- use console to look at `/hoome/user/che` if the jar and script was downloaded and can be executed

**Comment by cdietrich** [comment]
p.s: and clear the browser cache to make sure current javaa script stuff from che is used
